// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwpbbiF085lHg-0Gw8-OJPOi4MAsy6WbQ',
    appId: '1:726833645656:web:13e4e034de15c564cf622d',
    messagingSenderId: '726833645656',
    projectId: 'registrationapp-6bae9',
    authDomain: 'registrationapp-6bae9.firebaseapp.com',
    storageBucket: 'registrationapp-6bae9.appspot.com',
    measurementId: 'G-MLSPJZM59S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh2m5v9MDN_pto_g5H3V22AHXwri5haqM',
    appId: '1:726833645656:android:f631469ebde64567cf622d',
    messagingSenderId: '726833645656',
    projectId: 'registrationapp-6bae9',
    storageBucket: 'registrationapp-6bae9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq5wRsn1OYfkpUK9HtEP0GRCJOvCHbpPA',
    appId: '1:726833645656:ios:f16b1e444a9247f9cf622d',
    messagingSenderId: '726833645656',
    projectId: 'registrationapp-6bae9',
    storageBucket: 'registrationapp-6bae9.appspot.com',
    iosClientId: '726833645656-v4arhpkf7gqt1ft6f01306k8ea7sdaeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.signUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq5wRsn1OYfkpUK9HtEP0GRCJOvCHbpPA',
    appId: '1:726833645656:ios:f16b1e444a9247f9cf622d',
    messagingSenderId: '726833645656',
    projectId: 'registrationapp-6bae9',
    storageBucket: 'registrationapp-6bae9.appspot.com',
    iosClientId: '726833645656-v4arhpkf7gqt1ft6f01306k8ea7sdaeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.signUp',
  );
}
